%% Electrode network mapping for BSEP-rsfMRI analysis
%
% Register electrode coordinates to resting-state fMRI anatomical space,
% assign Yeo network labels, render cortical network locations, and compute
% electrode distance relative to gray and white matter.
%
% This script is part of the mnl_BSEPrsfMRI workflow.
%
% Author: Maria Guadalupe Yanez Ramos
% Developed with scientific and technical guidance from Dora Hermes
% and the Multimodal Neuroimaging Lab (MNL) team.
% May 2026




clc;
clearvars;


%% Configuration

% Add project-specific code here.
% External dependencies should preferably be added separately or documented
% in the README.


projectDir = fileparts('');
localDataPath = fullfile(projectDir, 'data');
addpath(genpath([projectDir,'/code']));
subjects = { ...
    '01', ...
    '02' ...
    };

mmDistance = 3;
yeo = 7;
hem = [1 2];

ieegSession = 'ieeg01';
fmriSession = 'compact3T01';


%% Dependencies
%
% Required external toolboxes/repositories:
%   - vistasoft
%   - mnl_ieegBasics
%   - mnl_DataCuration
%   - SPM
%
% Required project functions are listed in the README.

%% Register electrode coordinates to resting-state fMRI T1 space

for iSub = 1:numel(subjects)

    subLabel = subjects{iSub};

    fprintf('Processing subject sub-%s...\n', subLabel);

    %% Load anatomical images

    % T1 image used for electrode localization. Usually saved in sourcedata
    % and freesurfer
    acpcT1Name = fullfile( ...
        localDataPath, ...
        'derivatives', ...
        'T1electrodeCoordinates', ...
        ['sub-' subLabel], ...
        ['sub-' subLabel '_ses-' fmriSession '_desc-acpc_T1w.nii']);

    acpcT1 = niftiRead(acpcT1Name);

    % Preprocessed T1 from fMRIPrep.
    T1preprocName = fullfile( ...
        localDataPath, ...
        'derivatives', ...
        'fmriprep', ...
        ['sub-' subLabel], ...
        ['ses-' fmriSession], ...
        'anat', ...
        ['sub-' subLabel '_ses-' fmriSession '_desc-preproc_T1w.nii.gz']);

    T1preproc = niftiRead(T1preprocName);

    %% Compute transformation to resting-state fMRI T1 space

    acpc2rsfMRIXform = ssf_rsfMRIAlignToT1( ...
        acpcT1, ...
        T1preproc, ...
        [], ...
        false, ...
        1);

    %% Apply transformation to T1 image for quality control

    T1check = acpcT1;

    T1check.qto_xyz = acpc2rsfMRIXform;
    T1check.qto_ijk = inv(acpc2rsfMRIXform);
    T1check.sto_xyz = acpc2rsfMRIXform;
    T1check.sto_ijk = inv(acpc2rsfMRIXform);

    T1checkName = fullfile( ...
        localDataPath, ...
        'derivatives', ...
        'fmriprep', ...
        ['sub-' subLabel], ...
        ['ses-' fmriSession], ...
        'anat', ...
        'space_checking.nii');

    niftiWrite(T1check, T1checkName);

    %% Transform electrode coordinates

    electrodesTsvName = fullfile( ...
        localDataPath, ...
        ['sub-' subLabel], ...
        ['ses-' ieegSession], ...
        'ieeg', ...
        ['sub-' subLabel '_ses-' ieegSession '_electrodes.tsv']);

    elecTable = readtable( ...
        electrodesTsvName, ...
        'FileType', 'text', ...
        'Delimiter', '\t', ...
        'TreatAsEmpty', {'N/A', 'n/a'});

    acpcXYZ = [elecTable.x, elecTable.y, elecTable.z];

    rsXYZ = acpc2rsfMRIXform * ...
        acpcT1.qto_ijk * ...
        [acpcXYZ, ones(height(elecTable), 1)]';

    rsXYZ = rsXYZ(1:3, :)';

    %% Save electrodes in resting-state fMRI T1 space

    elecTableRs = elecTable;

    elecTableRs.x = rsXYZ(:, 1);
    elecTableRs.y = rsXYZ(:, 2);
    elecTableRs.z = rsXYZ(:, 3);

    electrodeOutputDir = fullfile( ...
        localDataPath, ...
        'derivatives', ...
        'electrodes2rsfMRI', ...
        ['sub-' subLabel]);

    if ~exist(electrodeOutputDir, 'dir')
        mkdir(electrodeOutputDir);
    end

    electrodesRsTsvName = fullfile( ...
        electrodeOutputDir, ...
        ['sub-' subLabel '_ses-' ieegSession ...
         '_space-rsT1_electrodes.tsv']);

    writetable( ...
        elecTableRs, ...
        electrodesRsTsvName, ...
        'FileType', 'text', ...
        'Delimiter', '\t');

    %% Write electrode positions to image for quality control

    ieeg_position2reslicedImage(rsXYZ, T1checkName);

    %% Create GIfTI surface files in T1 space

    freesurferDir = fullfile( ...
        localDataPath, ...
        'derivatives', ...
        'freesurfer', ...
        ['sub-' subLabel]);

    ieeg_FSsurf2T1space(freesurferDir, []);

end

%% Assign Yeo network to each electrode

ssf_assign_electrodes_to_yeo( ...
    localDataPath, ...
    mmDistance, ...
    subjects, ...
    yeo);

%% Render Yeo networks and electrodes

ssf_render_yeo_networks( ...
    localDataPath, ...
    subjects, ...
    hem, ...
    yeo);

%% Measure electrode distance to gray and white matter
%
% Output:
%   localDataPath/derivatives/gm_wmDistance/

distLim = 4; % mm

for iSub = 1:numel(subjects)

    subLabel = subjects{iSub};

    %% Load transformed electrode coordinates

    electrodesTsvName = fullfile( ...
        localDataPath, ...
        'derivatives', ...
        'electrodes2rsfMRI', ...
        ['sub-' subLabel], ...
        ['sub-' subLabel '_ses-' ieegSession ...
         '_space-rsT1_electrodes.tsv']);

    locInfo = readtable( ...
        electrodesTsvName, ...
        'FileType', 'text', ...
        'Delimiter', '\t', ...
        'TreatAsEmpty', {'N/A', 'n/a'});

    %% Load cortical surfaces

    freesurferDir = fullfile( ...
        localDataPath, ...
        'derivatives', ...
        'freesurfer', ...
        ['sub-' subLabel]);

    gL_pial = gifti(fullfile(freesurferDir, 'pial.L.surf.gii'));
    gR_pial = gifti(fullfile(freesurferDir, 'pial.R.surf.gii'));

    gL_white = gifti(fullfile(freesurferDir, 'white.L.surf.gii'));
    gR_white = gifti(fullfile(freesurferDir, 'white.R.surf.gii'));

    %% Calculate relative gray/white matter distance

    gmWm = ieeg_eldist2pial2white( ...
        locInfo, ...
        gL_pial, ...
        gR_pial, ...
        gL_white, ...
        gR_white, ...
        distLim);

    %% Save results

    ElectrodeName    = locInfo.name;
    RelativeDistance = gmWm.rel_dist;

    gmWmTable = table(ElectrodeName, RelativeDistance);

    gmWmOutputDir = fullfile( ...
        localDataPath, ...
        'derivatives', ...
        'gm_wmDistance', ...
        ['sub-' subLabel]);

    if ~exist(gmWmOutputDir, 'dir')
        mkdir(gmWmOutputDir);
    end

    gmWmName = fullfile( ...
        gmWmOutputDir, ...
        ['sub-' subLabel '_ses-' ieegSession '_gm_wm.tsv']);

    writetable( ...
        gmWmTable, ...
        gmWmName, ...
        'FileType', 'text', ...
        'Delimiter', '\t');

end